# Generated by Django 5.1.3 on 2024-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanfund',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='loan_funds', to='loans.loancustomer'),
        ),
    ]
