# Generated by Django 5.1.3 on 2024-11-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loanfund_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfund',
            name='bank_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_funds', to='loans.bank'),
            preserve_default=False,
        ),
    ]
