# Generated by Django 5.1.3 on 2024-11-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanfund_bank_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanfund',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
