# Generated by Django 5.1.3 on 2024-11-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_totalfunds_fund_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='max_duration',
            field=models.IntegerField(help_text='Maximum duration in years'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='min_duration',
            field=models.IntegerField(help_text='Minimum duration in years'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='requested_duration',
            field=models.IntegerField(blank=True, help_text='Requested duration in years', null=True),
        ),
    ]
