# Generated by Django 5.1.3 on 2024-11-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_loan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_accepted',
        ),
    ]
